### PR TITLE
Migrate Tests

### PR DESCRIPTION
**Pull request by jeff-hernandez**
Tests were migrated to GitHub Actions.

### CODE REVIEW

**Review by rwedge — COMMENTED** [review]
The scheduler is new test content - perhaps we should have a PR that only ports the existing tests first.

**Comment by jeff-hernandez** [comment]
Sure, I can separate the scheduler into another PR

**Comment by rwedge** [comment]
When we do add the scheudre, I think we'll need to add the featuretools release/main concept in order  to get the most usefulness out of it

**Comment by jeff-hernandez** [comment]
Sounds good. We may need to update the circleci action.

**Review by rwedge — APPROVED** [review]
Looks good

**Pull request merged**
